// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBirb2UzrybDT6C2qmei87v9LjGVtmDorY',
    appId: '1:241621103271:web:125290cf2cb00114ed6182',
    messagingSenderId: '241621103271',
    projectId: 'lab-test-first-day',
    authDomain: 'lab-test-first-day.firebaseapp.com',
    storageBucket: 'lab-test-first-day.appspot.com',
    measurementId: 'G-M85G2M9V52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKcjgHcrPRVWTuYwNYyxKGSR4zm5XRjcY',
    appId: '1:241621103271:android:dd1f2ad6644d99ebed6182',
    messagingSenderId: '241621103271',
    projectId: 'lab-test-first-day',
    storageBucket: 'lab-test-first-day.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpo9cupAcxUQR_X3LLlMraacK34M7nNOk',
    appId: '1:241621103271:ios:fef155d550cbf406ed6182',
    messagingSenderId: '241621103271',
    projectId: 'lab-test-first-day',
    storageBucket: 'lab-test-first-day.appspot.com',
    iosClientId: '241621103271-0b9dj0ca990pipdqhautm738jv8mbkn8.apps.googleusercontent.com',
    iosBundleId: 'com.example.labActivitySaturday',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpo9cupAcxUQR_X3LLlMraacK34M7nNOk',
    appId: '1:241621103271:ios:fef155d550cbf406ed6182',
    messagingSenderId: '241621103271',
    projectId: 'lab-test-first-day',
    storageBucket: 'lab-test-first-day.appspot.com',
    iosClientId: '241621103271-0b9dj0ca990pipdqhautm738jv8mbkn8.apps.googleusercontent.com',
    iosBundleId: 'com.example.labActivitySaturday',
  );
}
